[build-system]
requires = ['setuptools', 'wheel', 'scikit-build', 'cmake', 'ninja', 'requests', 'portalocker', 'numpy', 'mpi4py', 'sphinxcontrib-moderncmakedomain']
build-backend = 'setuptools.build_meta'
