// SPDX-FileCopyrightInfo: Copyright © DUNE Project contributors, see file LICENSE.md in module root
// SPDX-License-Identifier: LicenseRef-GPL-2.0-only-with-DUNE-exception
#ifndef DUNE_COMMON_CONFIG_HH
#define DUNE_COMMON_CONFIG_HH

/**
 * The following file is generated by the build system, and is typically found in the
 * `[build]/include' build directory, or is placed in the installed include directory.
 * It contains some preprocessor constants and configurations that can only be determined
 * at configuration time, by inspecting the system, the compiler, or the set of libraries
 * found.
 **/
#include <dune-common-config.hh>

#endif // DUNE_COMMON_CONFIG_HH
